language: csharp
solution: MIB.sln
install:
  - nuget restore MIB.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" MIB.sln
  - cd MIB.Test
  - mono ../testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./bin/Nunit/MIB.Test.dll
