language: csharp
solution: MIB.sln
install:
  - nuget restore MIB.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.Runners.3.0.1/tools/nunit-console.exe ./MIB.Tests/bin/Release/MIB.dll
